const personalBanking = [
  "Personal Banking|Digital banking|Ways to bank|Explore mobile banking",
  "Personal Banking|Digital banking|Ways to bank|Explore Online Banking",
  "Personal Banking|Digital banking|Ways to bank|Bank from home",
  "Personal Banking|Digital banking|Ways to bank|Register for Online Banking",
  "Personal Banking|Digital banking|Ways to bank|Paying in cheques online",
  "Personal Banking|Digital banking|Safe online banking|Digital confidence",
  "Personal Banking|Digital banking|Safe online banking|Control your privacy and data",
  "Personal Banking|Digital banking|Safe online banking|Digital Eagles",
  "Personal Banking|Digital banking|Safe online banking|Digitally safe quiz",
  "Personal Banking|Digital banking|Fraud worries|Fraud and protection",
  "Personal Banking|Digital banking|Fraud worries|How to report fraud",
  "Personal Banking|Digital banking|Fraud worries|Phone number checker",
  "Personal Banking|Digital banking|Fraud worries|Protecting your account",
  "Personal Banking|Digital banking|Fraud worries|Latest scams",
  "Personal Banking|Digital banking|Support|How can I create an IBAN?",
  "Personal Banking|Digital banking|Support|Switching your bank account to Barclays",
  "Personal Banking|Digital banking|Support|Linking accounts from other banks",
  "Personal Banking|Digital banking|Support|Jargon buster",
  "Personal Banking|Bank accounts|Everyday accounts|Compare current accounts",
  "Personal Banking|Bank accounts|Everyday accounts|Student bank accounts",
  "Personal Banking|Bank accounts|Everyday accounts|Children's bank accounts",
  "Personal Banking|Bank accounts|Everyday accounts|Foreign currency accounts",
  "Personal Banking|Bank accounts|Everyday accounts|Overdrafts",
  "Personal Banking|Bank accounts|Rewards|Barclays Avios Rewards",
  "Personal Banking|Bank accounts|Rewards|Barclays Blue Rewards",
  "Personal Banking|Bank accounts|Rewards|Cashback",
  "Personal Banking|Bank accounts|Rewards|Loyalty cards",
  "Personal Banking|Bank accounts|Rewards|Subscriptions",
  "Personal Banking|Bank accounts|Making Payments|Explore all payment services",
  "Personal Banking|Bank accounts|Making Payments|International payments",
  "Personal Banking|Bank accounts|Making Payments|Foreign currency",
  "Personal Banking|Bank accounts|Making Payments|Paperless documents",
  "Personal Banking|Bank accounts|Making Payments|Debit cards",
  "Personal Banking|Savings|Savings accounts|Compare savings accounts",
  "Personal Banking|Savings|Savings accounts|Guide to savings",
  "Personal Banking|Savings|Savings accounts|Children's savings accounts",
  "Personal Banking|Savings|Savings accounts|All interest rates",
  "Personal Banking|Savings|Cash ISAS|Compare ISA accounts",
  "Personal Banking|Savings|Cash ISAS|Guide to ISAS",
  "Personal Banking|Savings|Cash ISAS|Managing your Help to Buy ISA",
  "Personal Banking|Savings|Bonds|Compare bonds accounts",
  "Personal Banking|Investments|Investment accounts|All investment options",
  "Personal Banking|Investments|Investment accounts|Plan & Invest",
  "Personal Banking|Investments|Investment accounts|All Ready-made Investments",
  "Personal Banking|Investments|Investment accounts|Investment ISA",
  "Personal Banking|Investments|Investment accounts|Investment Account",
  "Personal Banking|Investments|Investment accounts|Self-Invested Personal Pension (SIPP)",
  "Personal Banking|Investments|Investment accounts|Investment costs",
  "Personal Banking|Investments|Investing with Barclays|New to investing",
  "Personal Banking|Investments|Investing with Barclays|Investments explained",
  "Personal Banking|Investments|Investing with Barclays|All news and research",
  "Personal Banking|Investments|Investing with Barclays|Our experts",
  "Personal Banking|Investments|Investing with Barclays|Frequently asked questions",
  "Personal Banking|Investments|Investment services|Smart Investor",
  "Personal Banking|Investments|Investment services|Transfer accounts",
  "Personal Banking|Investments|Investment services|International trading",
  "Personal Banking|Investments|Investment services|Barclays Price Improver",
  "Personal Banking|Investments|Investment services|Our research centre",
  "Personal Banking|Investments|Investment services|Individual Segregated Custody",
  "Personal Banking|Investments|Funds and shares|Find investments",
  "Personal Banking|Investments|Funds and shares|View our funds list",
  "Personal Banking|Investments|Funds and shares|How we select our active funds",
  "Personal Banking|Investments|Funds and shares|Most popular investments",
  "Personal Banking|Investments|Funds and shares|ESG investing",
  "Personal Banking|Investments|Funds and shares|IPOs and new issues",
  "Personal Banking|Borrowing|Our mortgages|Compare mortgages",
  "Personal Banking|Borrowing|Our mortgages|First-time buyer mortgages",
  "Personal Banking|Borrowing|Our mortgages|Borrow more on your mortgage",
  "Personal Banking|Borrowing|Our mortgages|Switch to a new rate",
  "Personal Banking|Borrowing|Our mortgages|Remortgaging with us",
  "Personal Banking|Borrowing|Our mortgages|Buying to let",
  "Personal Banking|Borrowing|Our mortgages|Shared ownership",
  "Personal Banking|Borrowing|Our mortgages|Offset mortgages",
  "Personal Banking|Borrowing|Mortgages tools and services|All mortgage services",
  "Personal Banking|Borrowing|Mortgages tools and services|Mortgage guidance and advice",
  "Personal Banking|Borrowing|Mortgages tools and services|All mortgage calculators",
  "Personal Banking|Borrowing|Mortgages tools and services|Agreement in Principle",
  "Personal Banking|Borrowing|Mortgages tools and services|Track an application",
  "Personal Banking|Borrowing|Mortgages tools and services|Managing your mortgage",
  "Personal Banking|Borrowing|Mortgages tools and services|Help to buy",
  "Personal Banking|Borrowing|Mortgages tools and services|Buy to let rates",
  "Personal Banking|Borrowing|Our loans|Compare loans",
  "Personal Banking|Borrowing|Our loans|Point-of-sale finance",
  "Personal Banking|Borrowing|Our loans|Top up an existing loan",
  "Personal Banking|Borrowing|Our loans|Car loans",
  "Personal Banking|Borrowing|Budgeting and debt support|What is a credit rating?",
  "Personal Banking|Borrowing|Budgeting and debt support|Budget planner",
  "Personal Banking|Borrowing|Budgeting and debt support|Consolidate your debt",
  "Personal Banking|Borrowing|Budgeting and debt support|Debt switch estimator ",
  "Personal Banking|Borrowing|Budgeting and debt support|Worried about mortgage repayments?",
  "Personal Banking|Borrowing|Budgeting and debt support|Money worries",
  "Personal Banking|Credit cards|Our cards|Compare credit cards",
  "Personal Banking|Credit cards|Our cards|Check your credit card eligibility",
  "Personal Banking|Credit cards|Our cards|Credit building credit cards",
  "Personal Banking|Credit cards|Manage your account|Barclaycard app",
  "Personal Banking|Credit cards|Manage your account|Log into Barclaycard",
  "Personal Banking|Credit cards|Support|Frequently asked questions",
  "Personal Banking|Credit cards|Support|What does APR mean?",
  "Personal Banking|Credit cards|Support|What is a credit rating?",
  "Personal Banking|Credit cards|Support|Contact Barclaycard",
  "Personal Banking|Insurance|Home insurance|All home insurance",
  "Personal Banking|Insurance|Home insurance|Barclays Home Insurance",
  "Personal Banking|Insurance|Home insurance|Barclays Landlord Insurance",
  "Personal Banking|Insurance|Life insurance|All life insurance",
  "Personal Banking|Insurance|Life insurance|Life insurance cover calculator",
  "Personal Banking|Insurance|Life insurance|Barclays Simple Life Insurance",
  "Personal Banking|Insurance|Life insurance|Life insurance for mortgage protection",
  "Personal Banking|Insurance|Travel insurance|All travel insurance",
  "Personal Banking|Insurance|Travel insurance|Travel Pack",
  "Personal Banking|Insurance|Travel insurance|Travel Plus Pack",
  "Personal Banking|Insurance|Travel insurance|Breakdown Cover Pack",
  "Personal Banking|Insurance|Travel insurance|Travel",
  "Personal Banking|Insurance|Tech insurance|All tech insurance",
  "Personal Banking|Insurance|Tech insurance|Tech Pack",
  "Personal Banking|Insurance|Tech insurance|Tech Pack Lite",
  "Personal Banking|Help and support|Your finances|Master your Moneyverse",
  "Personal Banking|Help and support|Your finances|Money management",
  "Personal Banking|Help and support|Your finances|Money Mentors",
  "Personal Banking|Help and support|Your finances|Spending within your means",
  "Personal Banking|Help and support|Your finances|Create a budget plan",
  "Personal Banking|Help and support|Worries|Money worries",
  "Personal Banking|Help and support|Worries|Coronavirus support",
  "Personal Banking|Help and support|Worries|Mental health support",
  "Personal Banking|Help and support|Worries|Event support",
  "Personal Banking|Help and support|Worries|Losing your job",
  "Personal Banking|Help and support|Support|What to do when someone dies",
  "Personal Banking|Help and support|Support|Accessbility and disability support",
  "Personal Banking|Help and support|Support|Customise my account",
  "Personal Banking|Help and support|Support|Control your privacy and data",
  "Personal Banking|Help and support|Support|Third-party access to bank accounts",
  "Personal Banking|Help and support|Support|Dormant and lost accounts",
  "Personal Banking|Help and support|Help|Visit our help centre"
];

const premierBanking = [
  "Premier Banking|Bank|Account and benefits|Premier Current Account",
  "Premier Banking|Bank|Account and benefits|All Current Accounts",
  "Premier Banking|Bank|Account and benefits|Overdrafts",
  "Premier Banking|Bank|Account and benefits|Switch to Barclays",
  "Premier Banking|Bank|Account and benefits|Premier Life",
  "Premier Banking|Bank|Rewards and offers|Barclays Avios Rewards",
  "Premier Banking|Bank|Rewards and offers|Barclays Blue rewards",
  "Premier Banking|Bank|Account services|Bank from home",
  "Premier Banking|Bank|Account services|Register for Online Banking",
  "Premier Banking|Bank|Account services|Customise my account",
  "Premier Banking|Bank|Account services|Control your data",
  "Premier Banking|Bank|Account services|The Barclays app",
  "Premier Banking|Bank|Payment Services|International Payments",
  "Premier Banking|Borrow|Loans and overdraft|Premier Barclayloan",
  "Premier Banking|Borrow|Loans and overdraft|Premier Flexiloan",
  "Premier Banking|Borrow|Loans and overdraft|Top up your loan",
  "Premier Banking|Borrow|Loans and overdraft|Overdrafts",
  "Premier Banking|Borrow|Credit cards|Compare credit cards",
  "Premier Banking|Borrow|Credit cards|Check your eligibility",
  "Premier Banking|Borrow|Credit cards|Balance transfer credit cards",
  "Premier Banking|Borrow|Credit cards|Purchase credit cards",
  "Premier Banking|Borrow|Credit cards|Credit building credit cards",
  "Premier Banking|Borrow|Credit cards|Reward credit cards",
  "Premier Banking|Borrow|Credit cards|Log in to mybarclaycard",
  "Premier Banking|Borrow|Tips|Ways to borrow",
  "Premier Banking|Borrow|Tips|Improve your credit rating",
  "Premier Banking|Borrow|Tips|Debt management",
  "Premier Banking|Borrow|Tips|Consolidating debt",
  "Premier Banking|Borrow|Tips|What does APR mean?",
  "Premier Banking|Borrow|Tools|Budget planner",
  "Premier Banking|Borrow|Tools|Credit Manager",
  "Premier Banking|Borrow|Tools|Credit card eligibility checker",
  "Premier Banking|Borrow|Tools|Loan repayment calculator",
  "Premier Banking|Credit cards|Apply for a Credit Card|Compare our cards",
  "Premier Banking|Credit cards|Apply for a Credit Card|Balance transfer credit cards",
  "Premier Banking|Credit cards|Apply for a Credit Card|Purchase offer credit cards",
  "Premier Banking|Credit cards|Apply for a Credit Card|Credit building credit cards",
  "Premier Banking|Credit cards|Apply for a Credit Card|Reward credit cards",
  "Premier Banking|Credit cards|Manage my Barclaycard|Log in to Barclaycard",
  "Premier Banking|Credit cards|Tools|Check your eligibility",
  "Premier Banking|Credit cards|Tools|Jargon Buster",
  "Premier Banking|Credit cards|Help & Support|FAQs",
  "Premier Banking|Credit cards|Help & Support|Contact us",
  "Premier Banking|Save and invest|Cash ISAs|Compare ISA accounts",
  "Premier Banking|Save and invest|Cash ISAs|Instant cash ISA",
  "Premier Banking|Save and invest|Cash ISAs|Guide to ISAs",
  "Premier Banking|Save and invest|Cash ISAs|Flexible Cash ISA – 1 Year",
  "Premier Banking|Save and invest|Cash ISAs|Premier Flexible Cash ISA – 1 Year",
  "Premier Banking|Save and invest|Cash ISAs|Managing your Help to Buy: ISA",
  "Premier Banking|Save and invest|Savings|Compare Savings accounts",
  "Premier Banking|Save and invest|Savings|Premier Savings and Investments",
  "Premier Banking|Save and invest|Savings|Everyday Saver",
  "Premier Banking|Save and invest|Savings|Blue Rewards Saver",
  "Premier Banking|Save and invest|Savings|Barclays Children’s Savings",
  "Premier Banking|Save and invest|Savings|All interest rates",
  "Premier Banking|Save and invest|Savings|Guide to Savings",
  "Premier Banking|Save and invest|Bonds|Compare Bonds accounts",
  "Premier Banking|Save and invest|Bonds|Fixed-rate Bond",
  "Premier Banking|Save and invest|Bonds|Flexible Bond – 2 Year",
  "Premier Banking|Save and invest|Bonds|Premier Flexible Bond – 2 Year",
  "Premier Banking|Save and invest|Investment accounts|All investment options",
  "Premier Banking|Save and invest|Investment accounts|Plan & Invest",
  "Premier Banking|Save and invest|Investment accounts|Ready-made Investments",
  "Premier Banking|Save and invest|Investment accounts|Investment ISA",
  "Premier Banking|Save and invest|Investment accounts|Investment Account",
  "Premier Banking|Save and invest|Investment accounts|Self-Invested Personal Pension (SIPP)",
  "Premier Banking|Save and invest|Investment accounts|Investment costs",
  "Premier Banking|Save and invest|Investment resources|Smart Investor",
  "Premier Banking|Save and invest|Investment resources|News and Research",
  "Premier Banking|Save and invest|Investment resources|Find investments",
  "Premier Banking|Save and invest|Investment resources|New to investing",
  "Premier Banking|Save and invest|Investment resources|Investments explained",
  "Premier Banking|Save and invest|Investment resources|Our Research Centre",
  "Premier Banking|Save and invest|Investment resources|Moving investments",
  "Premier Banking|Mortgage|Our mortgages|Premier mortgages",
  "Premier Banking|Mortgage|Our mortgages|All other mortgage services",
  "Premier Banking|Mortgage|Our mortgages|First-time buyers",
  "Premier Banking|Mortgage|Our mortgages|Remortgage to Barclays",
  "Premier Banking|Mortgage|Our mortgages|Moving home",
  "Premier Banking|Mortgage|Our mortgages|Buy-to-let",
  "Premier Banking|Mortgage|Our mortgages|Existing customers",
  "Premier Banking|Mortgage|Our mortgages|Help to buy mortgages",
  "Premier Banking|Mortgage|Our mortgages|Barclays Green Buy-to-Let mortgages",
  "Premier Banking|Mortgage|Products|All mortgages ",
  "Premier Banking|Mortgage|Products|Mortgage rates and charges",
  "Premier Banking|Mortgage|Products|Fixed-rate mortgages",
  "Premier Banking|Mortgage|Products|Tracker mortgages",
  "Premier Banking|Mortgage|Products|Offset mortgages",
  "Premier Banking|Mortgage|Products|Buy-to-let mortgages",
  "Premier Banking|Mortgage|Products|Family Springboard Mortgage",
  "Premier Banking|Mortgage|Tools|Mortgage tools",
  "Premier Banking|Mortgage|Tools|Mortgage calculators",
  "Premier Banking|Mortgage|Tools|Interest rate calculator",
  "Premier Banking|Mortgage|Tools|Base Rate Information",
  "Premier Banking|Mortgage|Tools|Offset mortgage calculator",
  "Premier Banking|Mortgage|Tools|Track an application",
  "Premier Banking|Mortgage|Apply|Agreement in principle (AIP)",
  "Premier Banking|Mortgage|Apply|Resume AiP",
  "Premier Banking|Mortgage|Apply|Switch Barclays mortgage",
  "Premier Banking|Mortgage|Apply|Making an appointment",
  "Premier Banking|Insure|Home insurance|Home insurance",
  "Premier Banking|Insure|Home insurance|Landlord insurance",
  "Premier Banking|Insure|Home insurance|Student Possessions insurance",
  "Premier Banking|Insure|Life insurance|All life insurance",
  "Premier Banking|Insure|Life insurance|Barclays Simple Life Insurance",
  "Premier Banking|Insure|Life insurance|Life insurance for mortgage holders",
  "Premier Banking|Insure|Travel insurance|All travel insurance",
  "Premier Banking|Insure|Travel insurance|Travel with breakdown cover",
  "Premier Banking|Insure|Travel insurance|Travel with breakdown cover and airport lounges",
  "Premier Banking|Insure|Travel insurance|Travel services",
  "Premier Banking|Insure|Phone and gadget cover|Phone and gadget insurance",
  "Premier Banking|Service and support|Help and support|Help and FAQs",
  "Premier Banking|Service and support|Help and support|Digisafe - fraud prevention",
  "Premier Banking|Service and support|Help and support| Lost and stolen card",
  "Premier Banking|Service and support|Help and support|Find a branch",
  "Premier Banking|Service and support|Help and support|Contact us",
  "Premier Banking|Service and support|Help and support|Coronavirus support",
  "Premier Banking|Service and support|Account services|Bank from home",
  "Premier Banking|Service and support|Account services|Online Banking",
  "Premier Banking|Service and support|Account services|The Barclays app",
  "Premier Banking|Service and support|Account services|Barclays Pingit",
  "Premier Banking|Service and support|Account services|Video Banking",
  "Premier Banking|Service and support|Account services|Control your data",
  "Premier Banking|Service and support|Account services|Accessibility",
  "Premier Banking|Service and support|Tools|Trading abroad checklist",
  "Premier Banking|Service and support|Tools|IBAN generator",
  "Premier Banking|Service and support|Tools|Digital confidence",
  "Premier Banking|Life's moments|Life events|Buying a car",
  "Premier Banking|Life's moments|Life events|Buying your first home",
  "Premier Banking|Life's moments|Life events|Improving your home",
  "Premier Banking|Life's moments|Life events|Travel",
  "Premier Banking|Life's moments|Life events|Getting married",
  "Premier Banking|Life's moments|Life events|Going to university",
  "Premier Banking|Life's moments|Life events|Helping younger generations",
  "Premier Banking|Life's moments|Life events|Explore all life moments",
  "Premier Banking|Life's moments|Difficult times|Coronavirus support",
  "Premier Banking|Life's moments|Difficult times|Money worries",
  "Premier Banking|Life's moments|Difficult times|Losing your job",
  "Premier Banking|Life's moments|Difficult times|Illness and debt",
  "Premier Banking|Life's moments|Difficult times|Mental health support",
  "Premier Banking|Life's moments|Difficult times|Gambling support",
  "Premier Banking|Life's moments|Difficult times|Bereavement",
  "Premier Banking|Life's moments|Money management|Saving money",
  "Premier Banking|Life's moments|Money management|Create a budget plan",
  "Premier Banking|Life's moments|Money management|Spending within your means",
  "Premier Banking|Life's moments|Money management|Explore money management hub",
  "Premier Banking|Life's moments|Everyday banking|Improving your digital skills",
  "Premier Banking|Life's moments|Everyday banking|Teaching children about money",
  "Premier Banking|Life's moments|Everyday banking|How to bank with us",
  "Premier Banking|Life's moments|Everyday banking|Accessibility and disability support",
  "Premier Banking|Life's moments|Everyday banking|Managing someone else’s finances"
];

const businessBanking = [
  "Business Banking|Accounts|Business type|All businesses",
  "Business Banking|Accounts|Business type|Start-up business",
  "Business Banking|Accounts|Business type|Up to £400k annual turnover",
  "Business Banking|Accounts|Business type|£400k to £6.5m annual turnover",
  "Business Banking|Accounts|Business type|Community (not-for-profit)",
  "Business Banking|Accounts|Other accounts|Savings Account",
  "Business Banking|Accounts|Other accounts|Foreign currency account",
  "Business Banking|Accounts|Switch to Barclays|Options to switch",
  "Business Banking|Accounts|Help and support|Help and FAQs",
  "Business Banking|Accounts|Help and support|Branch finder",
  "Business Banking|Accounts|Help and support|Lost cards",
  "Business Banking|Accounts|Help and support|Contact us",
  "Business Banking|Accounts|Help and support|Building resilience for Brexit",
  "Business Banking|Accounts|Help and support|Coronavirus help and support",
  "Business Banking|Accounts|Help and support|Support in difficult times",
  "Business Banking|Manage|Manage|Manage your business",
  "Business Banking|Manage|Manage|Money management",
  "Business Banking|Manage|Manage|Business insurance",
  "Business Banking|Manage|Manage|Invoice insurance",
  "Business Banking|Manage|Manage|Workplace pension",
  "Business Banking|Manage|Manage|Protection from fraud",
  "Business Banking|Manage|Manage|Business mandate change",
  "Business Banking|Manage|Manage|Dormant accounts",
  "Business Banking|Manage|Manage|Debit card",
  "Business Banking|Manage|Insights|SmartBusiness Dashboard",
  "Business Banking|Manage|Insights|Barclays Local Insights",
  "Business Banking|Manage|Insights|Articles",
  "Business Banking|Manage|Investments|Weekly market insights",
  "Business Banking|Manage|Investments|Featured podcast",
  "Business Banking|Manage|Help and support|Help and FAQs",
  "Business Banking|Manage|Help and support|Branch finder",
  "Business Banking|Manage|Help and support|Lost cards",
  "Business Banking|Manage|Help and support|Contact us",
  "Business Banking|Manage|Help and support|Building resilience for Brexit",
  "Business Banking|Manage|Help and support|Coronavirus help and support",
  "Business Banking|Manage|Help and support|Support in difficult times",
  "Business Banking|Borrow|Long term borrowing|All borrowing",
  "Business Banking|Borrow|Long term borrowing|Loans",
  "Business Banking|Borrow|Long term borrowing|Mortgages",
  "Business Banking|Borrow|Long term borrowing|Recovery Loan Scheme",
  "Business Banking|Borrow|Long term borrowing|Coronavirus Business Interruption Loan Scheme",
  "Business Banking|Borrow|Long term borrowing|Bounce Back Loan scheme",
  "Business Banking|Borrow|Long term borrowing|SIPP and SSAS loans",
  "Business Banking|Borrow|Flexible borrowing|Overdrafts",
  "Business Banking|Borrow|Flexible borrowing|Business credit cards and charge cards",
  "Business Banking|Borrow|Flexible borrowing|Asset finance services",
  "Business Banking|Borrow|Flexible borrowing|Invoice finance",
  "Business Banking|Borrow|Flexible borrowing|Retail finance",
  "Business Banking|Borrow|Help and support|Help and FAQs",
  "Business Banking|Borrow|Help and support|Branch finder",
  "Business Banking|Borrow|Help and support|Lost cards",
  "Business Banking|Borrow|Help and support|Contact us",
  "Business Banking|Borrow|Help and support|What can I do if my application is declined?",
  "Business Banking|Borrow|Help and support|Help with debt",
  "Business Banking|Borrow|Help and support|Building resilience for Brexit",
  "Business Banking|Borrow|Help and support|Coronavirus help and support",
  "Business Banking|Borrow|Help and support|Support in difficult times",
  "Business Banking|Account services|Account services|Ways to bank",
  "Business Banking|Account services|Account services|Banking from home",
  "Business Banking|Account services|Account services|Online banking",
  "Business Banking|Account services|Account services|The Barclays app",
  "Business Banking|Account services|Account services|Branch and telephony",
  "Business Banking|Account services|Account services|Business mandate change",
  "Business Banking|Account services|Account services|Control your data",
  "Business Banking|Account services|Account services|Accessibility",
  "Business Banking|Account services|Business tools|Invoicing",
  "Business Banking|Account services|Business tools|SmartBusiness Dashboard",
  "Business Banking|Account services|Business tools|Our partners",
  "Business Banking|Account services|Payments and collections|Accepting payments",
  "Business Banking|Account services|Payments and collections|Cash collection",
  "Business Banking|Account services|Payments and collections|Pingit for business",
  "Business Banking|Account services|Payments and collections|Foreign currency",
  "Business Banking|Account services|Payments and collections|IBAN generator",
  "Business Banking|Account services|Help and support|Help and FAQs",
  "Business Banking|Account services|Help and support|Branch finder",
  "Business Banking|Account services|Help and support|Lost cards",
  "Business Banking|Account services|Help and support|Contact us",
  "Business Banking|Account services|Help and support|Building resilience for Brexit",
  "Business Banking|Account services|Help and support|Coronavirus help and support",
  "Business Banking|Account services|Help and support|Support in difficult times",
  "Business Banking|Business abroad|Business abroad|Doing business abroad",
  "Business Banking|Business abroad|Business abroad|Foreign currency account",
  "Business Banking|Business abroad|Business abroad|Business abroad tools and features",
  "Business Banking|Business abroad|Business abroad|International payments",
  "Business Banking|Business abroad|Business abroad|Import documentary collections",
  "Business Banking|Business abroad|Business abroad|Import letters of credit",
  "Business Banking|Business abroad|Business abroad|Export documentary collections",
  "Business Banking|Business abroad|Business abroad|Export letters of credit",
  "Business Banking|Business abroad|Help and support|Help and FAQs",
  "Business Banking|Business abroad|Help and support|Branch finder",
  "Business Banking|Business abroad|Help and support|Lost cards",
  "Business Banking|Business abroad|Help and support|Contact us",
  "Business Banking|Business abroad|Help and support|Guide to importing",
  "Business Banking|Business abroad|Help and support|Guide to exporting",
  "Business Banking|Business abroad|Help and support|Building resilience for Brexit",
  "Business Banking|Business abroad|Help and support|Coronavirus help and support",
  "Business Banking|Business abroad|Help and support|Support in difficult times",
  "Business Banking|Sectors|Specialist industries|Sectors",
  "Business Banking|Sectors|Specialist industries|Social business",
  "Business Banking|Sectors|Specialist industries|Brokers and introducers",
  "Business Banking|Sectors|Specialist industries|Agriculture ",
  "Business Banking|Sectors|Specialist industries|High Growth & Entrepreneurs",
  "Business Banking|Sectors|Specialist industries|Real Estate",
  "Business Banking|Sectors|Women in Business|Women in business",
  "Business Banking|Sectors|Help and support|Help and FAQs",
  "Business Banking|Sectors|Help and support|Branch finder",
  "Business Banking|Sectors|Help and support|Lost cards",
  "Business Banking|Sectors|Help and support|Contact us",
  "Business Banking|Sectors|Help and support|Building resilience for Brexit",
  "Business Banking|Sectors|Help and support|Coronavirus help and support",
  "Business Banking|Sectors|Help and support|Support in difficult times",
  "Business Banking|Marketplace|Marketplace|View all partners",
  "Business Banking|Marketplace|Payment services|Barclaycard for business",
  "Business Banking|Marketplace|Payment services|Accept card payments with Barclaycard",
  "Business Banking|Marketplace|Insurance and pension services|Business insurance from Simply Business",
  "Business Banking|Marketplace|Insurance and pension services|Invoice insurance from Nimbla",
  "Business Banking|Marketplace|Insurance and pension services|Workplace pensions from Smart Pension",
  "Business Banking|Marketplace|Funding for growth|Invoice finance from MarketFinance",
  "Business Banking|Marketplace|Funding for growth|Asset Finance from Propel"
];

export const stringArr: Array<string> = [
  ...personalBanking,
  ...premierBanking,
  ...businessBanking
];

export const HEADERS = [
  "bankingType",
  "serviceType",
  "serviceInfoType",
  "serviceInfo"
] as const;

export const CREATE_DEPENDENCIES_UP_TO_INDEX = 4;

export const LABEL = "label";

export const ITEMS = "items";

export const LISTS_NAMES = [
  "bankingType",
  "serviceType",
  "serviceInfoType",
  "serviceInfo"
];

export const LISTS_LABELS = [
  "Banking type",
  "Service type",
  "Service information type",
  "Service information"
];


